### ISSUE TITLE
How to integrate a fund with transparency?

### ISSUE THREAD

**Issue by sadielsoftware** [sonatra/sonatra-jquery-sidebar#3]
Hello, how would the correct way to add a background to the document depending on the distance from the menu

example: [http://i.imgur.com/jJFQ6sF.png](http://i.imgur.com/jJFQ6sF.png)

**Comment by francoispluchino** [comment]
You must listen the `pan` event of Hammer and calculate the percent of opening of the sidebar, then add this value in the CSS opacity value (or rgba background-color) on the `$obfuscator` element.

**Comment by francoispluchino** [comment]
Or, more simple, you can display the `.sidebar-obfuscator` element on the `dragging` event:

```less
.sidebar-obfuscator {
    .sidebar-dragging ~ & {
        .transition(~"opacity @{sidebar-obfuscator-duration} ease");
        z-index: @zindex-sidebar-obfuscator;
        opacity: 1;
    }
}
```

But it's not correlated with the percent of the opening of the sidebar.
